ingress:
  enabled: true
  ingressClassName: traefik
  host: longhorn.home.arpa
  path: /
  pathType: Prefix
  tls: true
  tlsSecret: wildcard-home-arpa
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"

persistence:
  defaultClass: true 
  defaultClassReplicaCount: 1
  defaultDiskSelector:
    enable: true
    selector: "ssd"
  defaultNodeSelector:
    enable: true
    selector: "ssd"

defaultSettings:
  defaultDataPath: "/storage01"

service:
  ui:
    type: "ClusterIP"
preUpgradeChecker:
  jobEnabled: false
  upgradeVersionCheck: false

csi:
  attacherReplicaCount: 1
  provisionerReplicaCount: 1
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1

longhornManager:
  log:
    format: "json"

lonhornDriver:
  log:
    format: "json"
