apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"  
spec:
  project: default
  sources:
    - repoURL: git@github.com:blogdoft/k3s-apps.git
      path: artifacts/rancher/manifests
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true    